name: esteira-ci-dev

on:
  push:
    branches:
      - snapshot

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 21 ]
    steps:
      - name: Checa o git
        uses: actions/checkout@v2

      - name: Faz o set JDK Java
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Build Maven
        run: mvn clean install

      - name: Roda os testes da aplicação
        run: mvn test

      - name: Cria uma release/tag no gitHub
        id: release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: snapshot

      - name: (DOCKER HUB) Faz o set do QEMU para
        uses: docker/setup-qemu-action@v2

      - name: (DOCKER HUB) Faz o set Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: (DOCKER HUB) Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: (DOCKER HUB) Build e push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT }}:snapshot

      - name: Criar PR para a master
        id: criar-pr
        uses: pyrbin/single-pr-updater@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          label: 🚀 release
          head: snapshot
          base: master
          title: Release ${{ steps.release.outputs.tag_name }}
          body: |
            ## [Release ${{ steps.release.outputs.tag_name }}](${{ steps.release.outputs.html_url }})
            ${{ steps.release.outputs.body }}
          draft: false

      - name: Resetar máquina virtual
        uses: actions/checkout@v2
        with:
          clean: true

      - name: (VERSAO) Instala o maven
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: (VERSAO) Atualiza versão no maven
        run: mvn -B versions:set -DnewVersion=${{ steps.release.outputs.tag_name }} -DgenerateBackupPoms=false

      - name: (VERSAO) Realiza o commit no pom da nova versão
        uses: stefanzweifel/git-auto-commit-action@v4