name: esteira-ci-dev

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11 ]
    steps:
      - name: Checa o git
        uses: actions/checkout@v2

      - name: Faz o set JDK Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build Maven
        run: mvn clean install

      - name: Roda os testes da aplicação
        run: mvn test

      - name: Cria uma release/tag no gitHub
        id: release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: (DOCKER HUB) Faz o set do QEMU para
        uses: docker/setup-qemu-action@v2

      - name: (DOCKER HUB) Faz o set Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: (DOCKER HUB) Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: (DOCKER HUB) Build e push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT }}:${{ steps.release.outputs.tag_name }}, ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT }}:latest

      - name: (VERSAO) Publicar release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.release.outputs.id }}